version: "3.9"

services:
  devquote-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devquote-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://devquote-postgres:5434/devquote?sslmode=disable"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "root"
      SERVER_PORT: "8080"
      REDIS_HOST: "devquote-redis"
      REDIS_PORT: "6379"
    networks:
      - devquote-network

networks:
  devquote-network:
    external: true
