version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: devquote-postgres
    ports:
      - "5434:5434"
    environment:
      POSTGRES_DB: devquote
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGPORT: 5434
    volumes:
      - devquote_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d devquote -h localhost -p 5434" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: devquote-redis
    ports:
      - "6379:6379"
    volumes:
      - devquote_redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  devquote-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devquote-backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5434/devquote?sslmode=disable"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "root"
      SERVER_PORT: "8080"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"

volumes:
  devquote_pgdata:
  devquote_redis_data:
