version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: devquote-redis
    ports:
      - "6379:6379"
    volumes:
      - devquote_redis_data:/data
    networks:
      - devquote-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  devquote_redis_data:

networks:
  devquote-network:
    external: true
